name: zig

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: mlugg/setup-zig@v2
        name: Set up zig
        with:
          version: 0.15.1

      - name: Build
        run: |
          zig build
      - name: Test
        run: |
          zig fmt --check src/*
